##########################################
# NAMESPACE
##########################################
apiVersion: v1
kind: Namespace
metadata:
  name: ns-2401147

---
##########################################
# SUPABASE SECRET
##########################################
apiVersion: v1
kind: Secret
metadata:
  name: music-frontend-secret
  namespace: ns-2401147
type: Opaque
stringData:
  VITE_SUPABASE_URL: "https://jzdolobncemqdqazgwoq.supabase.co"
  VITE_SUPABASE_ANON_KEY: "sb_publishable_hCPSbbO5pR1p1mGhG0HoYw_-o3CWhIY"

---
##########################################
# DEPLOYMENT (FRONTEND)
##########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-frontend
  namespace: ns-2401147
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-frontend
  template:
    metadata:
      labels:
        app: music-frontend
    spec:
      imagePullSecrets:
        - name: nexus-secret     # MUST BE CREATED BEFORE DEPLOYMENT

      containers:
      - name: music-frontend
        image: host.docker.internal:30085/datta-project/music-learning-platform:latest
        ports:
          - containerPort: 80

        env:
        - name: VITE_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: music-frontend-secret
              key: VITE_SUPABASE_URL

        - name: VITE_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: music-frontend-secret
              key: VITE_SUPABASE_ANON_KEY

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3

---
##########################################
# SERVICE
##########################################
apiVersion: v1
kind: Service
metadata:
  name: music-frontend-service
  namespace: ns-2401147
spec:
  selector:
    app: music-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
##########################################
# INGRESS (OPTIONAL)
##########################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-frontend-ingress
  namespace: ns-2401147
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: music.yourdomain.com   # CHANGE TO YOUR DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: music-frontend-service
                port:
                  number: 80
